### ISSUE TITLE
Blockmarket 1.0.0 won't load under Mac OS Yosemite

### ISSUE THREAD

**Issue by l3sny** [syscoin/blockmarket-desktop-public#232]
What I am getting is:
 A JavaScript error occurred in the main process

Uncaught Exception:
TypeError: Cannot read property 'show' of undefined
   at App.onActivate (/Applications/Blockmarket.app/Contents/Resources/app.asar/out/main.js:27:24)
   at emitTwo (events.js:106:13)
   at App.emit (events.js:194:7)

**Comment by dwasyluk** [comment]
Pls try the suggested 1.0.1 link in https://github.com/syscoin/blockmarket-desktop-public/issues/245, closing this as duplicate for now.
